vcc: Fix VCL_BOOL translation
When translating VCL-to-C, VCL_BOOL values are
translated verbatim, the stdbool.h file is not
included in vgc.c. On Debian this causes the
following error:
```
**** v1    CLI RX|Message from C-compiler:
**** v1    CLI RX|vgc.c: In function 'VGC_function_vcl_init':
**** v1    CLI RX|vgc.c:4402:26: error: 'false' undeclared (first use in this function)
**** v1    CLI RX| 4402 |           .hidevclname = false,
**** v1    CLI RX|      |                          ^~~~~
**** v1    CLI RX|vgc.c:702:1: note: 'false' is defined in header '<stdbool.h>'; this is probably fixable by adding '#include <stdbool.h>'
**** v1    CLI RX|  701 | #include <stddef.h>             // NULL, size_t
**** v1    CLI RX|  +++ |+#include <stdbool.h>
**** v1    CLI RX|  702 | #include <stdint.h>             // [u]int%d_t
**** v1    CLI RX|vgc.c:4402:26: note: each undeclared identifier is reported only once for each function it appears in
**** v1    CLI RX| 4402 |           .hidevclname = false,
**** v1    CLI RX|[1 lines truncated]
**** v1    CLI RX|Running C-compiler failed, exited with 1
**** v1    CLI RX|VCL compilation failed
```
This commit fixes this by translating the boolean
values (true/false) to int values (0/1).
Since the strings are already checked to be valid
identifiers we only check for the first letter
in order to discriminate true from false.